project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_url_env: CROWDIN_BASE_URL
base_path: .
preserve_hierarchy: true
files:
  [
    {
      "source": "/warp-ios/Resources/en.lproj/Localizable.xcstrings",
      "dest": "/warp-ios/%original_path%/%original_file_name%",
      "translation": "/warp-ios/Resources/%two_letters_code%.lproj/Localizable.xcstrings",
      "type": "macosx",
    }
  ]